import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { DataProvider } from "@/Context/dataContext";
import SplashWrapper from "@/components/SplashWrapper";

import { JetBrains_Mono } from "next/font/google";

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  style: ["normal", "italic"],
  variable: "--font-jetbrains",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="">
      <body className={jetbrainsMono.className}>
        <SplashWrapper></SplashWrapper>
        <DataProvider>{children}</DataProvider>
      </body>
    </html>
  );
}
