import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { DataProvider } from "@/Context/dataContext";
import SplashWrapper from "@/components/SplashWrapper";

import { JetBrains_Mono } from "next/font/google";
import NavBar from "@/components/NavBar";
import { ThemeProvider } from "@/Context/ThemeContext";
import SplashScreen from "@/components/SplashScreen";
import ParticleBackground from "@/components/ParticleBackground";
import Footer from "@/components/Footer";

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  style: ["normal", "italic"],
  variable: "--font-jetbrains",
});

export const metadata = {
  title: "CoDeHaSiB | My Portfolio",
  description: "Generated by Hasib",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={jetbrainsMono.className}>
        <ThemeProvider>
          <ParticleBackground></ParticleBackground>
          <SplashWrapper></SplashWrapper>
          <NavBar></NavBar>
          <DataProvider>{children}</DataProvider>
          <Footer></Footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
